homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.1.35'
  client_id: zigbee_odroid
serial:
  port: /dev/ttyUSB0
  baudrate: 115200
advanced:
  rtscts: false
devices:
